event = {
	// FORMULA E 2018/19 SEASON OUTLINE
	"0": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 01,
		"name": "Ad Diriyah ePrix",
		"circuit": "Riyadh Street Circuit",
		"location": "Ad Diriyah, Saudi Arabia",
		"session": "Race",
		"time": 1544875200,
		"laps": "45' + 1",
		"length": 2700
	},
	"1": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 02,
		"name": "Marrakesh ePrix",
		"circuit": "Moulay El Hassan",
		"location": "Marrakesh, Morocco",
		"session": "Race",
		"time": 1547305380,
		"laps": "45' + 1",
		"length": 2700
	},
	"2": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 03,
		"name": "Santiago ePrix",
		"circuit": "Parque O'Higgins",
		"location": "Santiago, Chile",
		"session": "Race *",
		"time": 1548504000,
		"laps": "45' + 1",
		"length": 2700
	},
	"3": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 04,
		"name": "Mexico City ePrix",
		"circuit": "Hermanos Rodríguez",
		"location": "Mexico City, Mexico",
		"session": "Race *",
		"time": 1550318400,
		"laps": "45' + 1",
		"length": 2700
	},
	"4": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 05,
		"name": "Hong Kong ePrix",
		"circuit": "Central Harbourfront",
		"location": "Hong Kong",
		"session": "Race *",
		"time": 1552219200,
		"laps": "45' + 1",
		"length": 2700
	},
	"5": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 06,
		"name": "Sanya ePrix",
		"circuit": "Sanya Street Circuit",
		"location": "Sanya, China",
		"session": "Race *",
		"time": 1553342400,
		"laps": "45' + 1",
		"length": 2700
	},
	"6": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 07,
		"name": "Rome ePrix",
		"circuit": "Circuto Cittadino dell'EUR",
		"location": "Rome, Italy",
		"session": "Race *",
		"time": 1555156800,
		"laps": "45' + 1",
		"length": 2700
	},
	"7": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 08,
		"name": "Paris ePrix",
		"circuit": "Circuit des Invalides",
		"location": "Paris, France",
		"session": "Race *",
		"time": 1556366400,
		"laps": "45' + 1",
		"length": 2700
	},
	"8": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 09,
		"name": "Monaco ePrix",
		"circuit": "Circuit de Monaco",
		"location": "Monte Carlo, Monaco",
		"session": "Race *",
		"time": 1557576000,
		"laps": "45' + 1",
		"length": 2700
	},
	"9": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 10,
		"name": "Berlin ePrix",
		"circuit": "Tempelhof Airport",
		"location": "Berlin, Germany",
		"session": "Race *",
		"time": 1558785600,
		"laps": "45' + 1",
		"length": 2700
	},
	"10": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 11,
		"name": "Bern ePrix",
		"circuit": "TBA",
		"location": "Switzerland",
		"session": "Race *",
		"time": 1561204800,
		"laps": "45' + 1",
		"length": 2700
	},
	"11": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 13,
		"name": "New York City ePrix",
		"circuit": "Brooklyn Street Circuit",
		"location": "New Jersey, USA",
		"session": "Race *",
		"time": 1563019200,
		"laps": "45' + 1",
		"length": 2700
	},
	"12": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 14,
		"name": "New York City ePrix",
		"circuit": "Brooklyn Street Circuit",
		"location": "New Jersey, USA",
		"session": "Race *",
		"time": 1563105600,
		"laps": "45' + 1",
		"length": 2700
	},
	// FORMULA ONE 2019 SEASON OUTLINE
	"13": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 1,
		"name": "Australian Grand Prix",
		"circuit": "Albert Park",
		"location": "Melbourne, Australia",
		"session": "Race *",
		"time": 1552824000,
		"laps": 58,
		"length": 7200
	},
	"14": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 2,
		"name": "Bahrain Grand Prix",
		"circuit": "Bahrain International",
		"location": "Sakhir, Bahrain",
		"session": "Race *",
		"time": 1554033600,
		"laps": 57,
		"length": 7200
	},
	"15": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 3,
		"name": "Chinese Grand Prix",
		"circuit": "Shanghai",
		"location": "Shanghai, China",
		"session": "Race *",
		"time": 1555243200,
		"laps": 56,
		"length": 7200
	},
	"16": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 4,
		"name": "Azerbaijan Grand Prix",
		"circuit": "Baku",
		"location": "Baku, Azerbaijan",
		"session": "Race *",
		"time": 1556452800,
		"laps": 51,
		"length": 7200
	},
	"17": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 5,
		"name": "Spanish Grand Prix",
		"circuit": "Barcelona-Catalunya",
		"location": "Montmeló, Spain",
		"session": "Race *",
		"time": 1557662400,
		"laps": 66,
		"length": 7200
	},
	"18": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 6,
		"name": "Monaco Grand Prix",
		"circuit": "Monaco",
		"location": "Monte Carlo, Monaco",
		"session": "Race *",
		"time": 1558872000,
		"laps": 78,
		"length": 7200
	},
	"19": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 7,
		"name": "Canadian Grand Prix",
		"circuit": "Gilles Villeneuve",
		"location": "Montreal, Canada",
		"session": "Race *",
		"time": 1560081600,
		"laps": 70,
		"length": 7200
	},
	"20": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 8,
		"name": "French Grand Prix",
		"circuit": "Paul Ricard",
		"location": "Le Castellet, France",
		"session": "Race *",
		"time": 1561291200,
		"laps": 53,
		"length": 7200
	},
	"21": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 9,
		"name": "Austrian Grand Prix",
		"circuit": "Red Bull Ring",
		"location": "Spielberg, Austria",
		"session": "Race *",
		"time": 1561896000,
		"laps": 71,
		"length": 7200
	},
	"22": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 10,
		"name": "British Grand Prix",
		"circuit": "Silverstone",
		"location": "Silverstone, United Kingdom",
		"session": "Race *",
		"time": 1563105600,
		"laps": 52,
		"length": 7200
	},
	"23": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 11,
		"name": "German Grand Prix",
		"circuit": "Hockenheimring",
		"location": "Hockenheim, Germany",
		"session": "Race *",
		"time": 1564315200,
		"laps": 67,
		"length": 7200
	},
	"24": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 12,
		"name": "Hungarian Grand Prix",
		"circuit": "Hungaroring",
		"location": "Mogyoród, Hungary",
		"session": "Race *",
		"time": 1564920000,
		"laps": 70,
		"length": 7200
	},
	"25": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 13,
		"name": "Belgian Grand Prix",
		"circuit": "Spa-Francorchamps",
		"location": "Stavelot, Belgium",
		"session": "Race *",
		"time": 1567339200,
		"laps": 44,
		"length": 7200
	},
	"26": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 14,
		"name": "Italian Grand Prix",
		"circuit": "Monza",
		"location": "Monza, Italy",
		"session": "Race *",
		"time": 1567944000,
		"laps": 53,
		"length": 7200
	},
	"27": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 15,
		"name": "Singapore Grand Prix",
		"circuit": "Marina Bay",
		"location": "Marina Bay, Singapore",
		"session": "Race *",
		"time": 1569153600,
		"laps": 61,
		"length": 7200
	},
	"28": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 16,
		"name": "Russian Grand Prix",
		"circuit": "Sochi",
		"location": "Sochi, Russia",
		"session": "Race *",
		"time": 1569758400,
		"laps": 53,
		"length": 7200
	},
	"29": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 17,
		"name": "Japanese Grand Prix",
		"circuit": "Suzuka",
		"location": "Suzuka, Japan",
		"session": "Race *",
		"time": 1570968000,
		"laps": 53,
		"length": 7200
	},
	"30": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 18,
		"name": "Mexican Grand Prix",
		"circuit": "Hermanos Rodríguez",
		"location": "Mexico City, Mexico",
		"session": "Race *",
		"time": 1572177600,
		"laps": 71,
		"length": 7200
	},
	"31": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 19,
		"name": "United States Grand Prix",
		"circuit": "Circuit of the Americas",
		"location": "Austin, Texas",
		"session": "Race *",
		"time": 1572782400,
		"laps": 56,
		"length": 7200
	},
	"32": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 20,
		"name": "Brazilian Grand Prix",
		"circuit": "Interlagos",
		"location": "São Paulo, Brazil",
		"session": "Race *",
		"time": 1573992000,
		"laps": 71,
		"length": 7200
	},
	"33": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 21,
		"name": "Abu Dhabi Grand Prix",
		"circuit": "Yas Marina",
		"location": "Abu Dhabi, UAE",
		"session": "Race *",
		"time": 1575201600,
		"laps": 55,
		"length": 7200
	},
	// Asian LMS 2018/19 SEASON OUTLINE
	"34": {
		"series": "Asian Le Mans Series",
		"symbol": "AsianLMS",
		"round": 1,
		"name": "4h Shanghai",
		"circuit": "Shanghai",
		"location": "Shanghai, China",
		"session": "Race *",
		"time": 1543147200,
		"laps": false,
		"length": 14400
	},
	"35": {
		"series": "Asian Le Mans Series",
		"symbol": "AsianLMS",
		"round": 2,
		"name": "4h Fuji",
		"circuit": "Fuji Speedway",
		"location": "Oyama, Japan",
		"session": "Race *",
		"time": 1544356800,
		"laps": false,
		"length": 14400
	},
	"36": {
		"series": "Asian Le Mans Series",
		"symbol": "AsianLMS",
		"round": 3,
		"name": "4 Hours of Buriram",
		"circuit": "Chang International",
		"location": "Buriram, Thailand",
		"session": "Race",
		"time": 1547268300,
		"laps": false,
		"length": 14400
	},
	"37": {
		"series": "Asian Le Mans Series",
		"symbol": "AsianLMS",
		"round": 4,
		"name": "4 Hours of Sepang",
		"circuit": "Sepang International",
		"location": "Selangor, Malaysia",
		"session": "Race *",
		"time": 1551009600,
		"laps": false,
		"length": 14400
	},
	//WEC 2018/19 SEASON OUTLINE
	"38": {
		"series": "World Endurance Championship",
		"symbol": "WEC",
		"round": 06,
		"name": "1000 Miles of Sebring",
		"circuit": "Sebring",
		"location": "Highlands County, Florida",
		"session": "Race *",
		"time": 1552651200,
		"laps": "TBD",
		"length": 7200
	},
	"39": {
		"series": "World Endurance Championship",
		"symbol": "WEC",
		"round": 07,
		"name": "6 Hours of Spa-Francorchamps",
		"circuit": "Spa-Francorchamps",
		"location": "Stavelot, Belgium",
		"session": "Race *",
		"time": 1556967600,
		"laps": false,
		"length": 21600
	},
	"40": {
		"series": "World Endurance Championship",
		"symbol": "WEC",
		"round": 08,
		"name": "24 Hours of Le Mans",
		"circuit": "la Sarthe",
		"location": "Le Mans, France",
		"session": "Race *",
		"time": 1560603600,
		"laps": false,
		"length": 86400
	},
	// FORMULA E 2018/19 SEASON ROUND 01 DETAILS
	"41": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 01,
		"name": "Ad Diriyah ePrix",
		"circuit": "Riyadh Street Circuit",
		"location": "Ad Diriyah, Saudi Arabia",
		"session": "Free Practice 1",
		"time": 1544846400,
		"laps": false,
		"length": 2700
	},
	"42": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 01,
		"name": "Ad Diriyah ePrix",
		"circuit": "Riyadh Street Circuit",
		"location": "Ad Diriyah, Saudi Arabia",
		"session": "Free Practice 2",
		"time": 1544853900,
		"laps": false,
		"length": 1800
	},
	"43": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 01,
		"name": "Ad Diriyah ePrix",
		"circuit": "Riyadh Street Circuit",
		"location": "Ad Diriyah, Saudi Arabia",
		"session": "Qualifying",
		"time": 1544860200,
		"laps": false,
		"length": 2700
	},
	"44": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 01,
		"name": "Ad Diriyah ePrix",
		"circuit": "Riyadh Street Circuit",
		"location": "Ad Diriyah, Saudi Arabia",
		"session": "Super Pole",
		"time": 1544862900,
		"laps": false,
		"length": 900
	},
	// FORMULA E 2018/19 SEASON ROUND 02 DETAILS
	"45": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 02,
		"name": "Marrakesh ePrix",
		"circuit": "Moulay El Hassan",
		"location": "Marrakesh, Morocco",
		"session": "Free Practice 1",
		"time": 1547276400,
		"laps": false,
		"length": 2700
	},
	"46": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 02,
		"name": "Marrakesh ePrix",
		"circuit": "Moulay El Hassan",
		"location": "Marrakesh, Morocco",
		"session": "Free Practice 2",
		"time": 1547284500,
		"laps": false,
		"length": 1800
	},
	"47": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 02,
		"name": "Marrakesh ePrix",
		"circuit": "Moulay El Hassan",
		"location": "Marrakesh, Morocco",
		"session": "Qualifying",
		"time": 1547290800,
		"laps": false,
		"length": 2700
	},
	"48": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 02,
		"name": "Marrakesh ePrix",
		"circuit": "Moulay El Hassan",
		"location": "Marrakesh, Morocco",
		"session": "Super Pole",
		"time": 1547293500,
		"laps": false,
		"length": 900
	},
	"49": {
		"series": "Asian Le Mans Series",
		"symbol": "AsianLMS",
		"round": 3,
		"name": "4 Hours of Buriram",
		"circuit": "Chang International",
		"location": "Buriram, Thailand",
		"session": "Free Practice 1",
		"time": 1547170800,
		"laps": false,
		"length": 5400
	},
	"50": {
		"series": "Asian Le Mans Series",
		"symbol": "AsianLMS",
		"round": 3,
		"name": "4 Hours of Buriram",
		"circuit": "Chang International",
		"location": "Buriram, Thailand",
		"session": "Free Practice 2",
		"time": 1547185200,
		"laps": false,
		"length": 4800
	},
	"51": {
		"series": "Asian Le Mans Series",
		"symbol": "AsianLMS",
		"round": 3,
		"name": "4 Hours of Buriram",
		"circuit": "Chang International",
		"location": "Buriram, Thailand",
		"session": "GT Qualifying",
		"time": 1547199300,
		"laps": false,
		"length": 900
	},
	"52": {
		"series": "Asian Le Mans Series",
		"symbol": "AsianLMS",
		"round": 3,
		"name": "4 Hours of Buriram",
		"circuit": "Chang International",
		"location": "Buriram, Thailand",
		"session": "LMP2 & LMP3 Qualifying",
		"time": 1547200800,
		"laps": false,
		"length": 900
	},
	"53": {
		"series": "Race of Champions",
		"symbol": "ROC",
		"round": "",
		"name": "Race of Champions",
		"circuit": "Hermanos Rodríguez",
		"location": "Mexico City, Mexico",
		"session": "ROC Nations Cup",
		"time": 1547924400,
		"laps": false,
		"length": 10800
	},
	"54": {
		"series": "Race of Champions",
		"symbol": "ROC",
		"round": "",
		"name": "Race of Champions",
		"circuit": "Hermanos Rodríguez",
		"location": "Mexico City, Mexico",
		"session": "Race of Champions",
		"time": 1548010800,
		"laps": false,
		"length": 10800
	},
}