event = {
	// FORMULA E 2018/19 SEASON OUTLINE
	"0": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 01,
		"name": "Ad Diriyah ePrix",
		"circuit": "Riyadh Street Circuit",
		"location": "Ad Diriyah, Saudi Arabia",
		"session": "Race",
		"time": 1544875200,
		"laps": "45' + 1",
		"distance": false,
		"length": 2700
	},
	"1": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 02,
		"name": "Marrakesh ePrix",
		"circuit": "Moulay El Hassan",
		"location": "Marrakesh, Morocco",
		"session": "Race",
		"time": 1547305380,
		"laps": "45' + 1",
		"distance": false,
		"length": 2700
	},
	"2": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 03,
		"name": "Santiago ePrix",
		"circuit": "Parque O'Higgins",
		"location": "Santiago, Chile",
		"session": "Race *",
		"time": 1548504000,
		"laps": "45' + 1",
		"distance": false,
		"length": 2700
	},
	"3": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 04,
		"name": "Mexico City ePrix",
		"circuit": "Hermanos Rodríguez",
		"location": "Mexico City, Mexico",
		"session": "Race *",
		"time": 1550318400,
		"laps": "45' + 1",
		"distance": false,
		"length": 2700
	},
	"4": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 05,
		"name": "Hong Kong ePrix",
		"circuit": "Central Harbourfront",
		"location": "Hong Kong",
		"session": "Race *",
		"time": 1552219200,
		"laps": "45' + 1",
		"distance": false,
		"length": 2700
	},
	"5": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 06,
		"name": "Sanya ePrix",
		"circuit": "Sanya Street Circuit",
		"location": "Sanya, China",
		"session": "Race *",
		"time": 1553342400,
		"laps": "45' + 1",
		"distance": false,
		"length": 2700
	},
	"6": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 07,
		"name": "Rome ePrix",
		"circuit": "Circuto Cittadino dell'EUR",
		"location": "Rome, Italy",
		"session": "Race *",
		"time": 1555156800,
		"laps": "45' + 1",
		"distance": false,
		"length": 2700
	},
	"7": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 08,
		"name": "Paris ePrix",
		"circuit": "Circuit des Invalides",
		"location": "Paris, France",
		"session": "Race *",
		"time": 1556366400,
		"laps": "45' + 1",
		"distance": false,
		"length": 2700
	},
	"8": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 09,
		"name": "Monaco ePrix",
		"circuit": "Circuit de Monaco",
		"location": "Monte Carlo, Monaco",
		"session": "Race *",
		"time": 1557576000,
		"laps": "45' + 1",
		"distance": false,
		"length": 2700
	},
	"9": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 10,
		"name": "Berlin ePrix",
		"circuit": "Tempelhof Airport",
		"location": "Berlin, Germany",
		"session": "Race *",
		"time": 1558785600,
		"laps": "45' + 1",
		"distance": false,
		"length": 2700
	},
	"10": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 11,
		"name": "Bern ePrix",
		"circuit": "TBA",
		"location": "Switzerland",
		"session": "Race *",
		"time": 1561204800,
		"laps": "45' + 1",
		"distance": false,
		"length": 2700
	},
	"11": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 13,
		"name": "New York City ePrix",
		"circuit": "Brooklyn Street Circuit",
		"location": "New Jersey, USA",
		"session": "Race *",
		"time": 1563019200,
		"laps": "45' + 1",
		"distance": false,
		"length": 2700
	},
	"12": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 14,
		"name": "New York City ePrix",
		"circuit": "Brooklyn Street Circuit",
		"location": "New Jersey, USA",
		"session": "Race *",
		"time": 1563105600,
		"laps": "45' + 1",
		"distance": false,
		"length": 2700
	},
	// FORMULA ONE 2019 SEASON OUTLINE
	"13": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 1,
		"name": "Australian Grand Prix",
		"circuit": "Albert Park",
		"location": "Melbourne, Australia",
		"session": "Race *",
		"time": 1552824000,
		"laps": 58,
		"distance": false,
		"length": 7200
	},
	"14": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 2,
		"name": "Bahrain Grand Prix",
		"circuit": "Bahrain International",
		"location": "Sakhir, Bahrain",
		"session": "Race *",
		"time": 1554033600,
		"laps": 57,
		"distance": false,
		"length": 7200
	},
	"15": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 3,
		"name": "Chinese Grand Prix",
		"circuit": "Shanghai",
		"location": "Shanghai, China",
		"session": "Race *",
		"time": 1555243200,
		"laps": 56,
		"distance": false,
		"length": 7200
	},
	"16": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 4,
		"name": "Azerbaijan Grand Prix",
		"circuit": "Baku",
		"location": "Baku, Azerbaijan",
		"session": "Race *",
		"time": 1556452800,
		"laps": 51,
		"distance": false,
		"length": 7200
	},
	"17": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 5,
		"name": "Spanish Grand Prix",
		"circuit": "Barcelona-Catalunya",
		"location": "Montmeló, Spain",
		"session": "Race *",
		"time": 1557662400,
		"laps": 66,
		"distance": false,
		"length": 7200
	},
	"18": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 6,
		"name": "Monaco Grand Prix",
		"circuit": "Monaco",
		"location": "Monte Carlo, Monaco",
		"session": "Race *",
		"time": 1558872000,
		"laps": 78,
		"distance": false,
		"length": 7200
	},
	"19": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 7,
		"name": "Canadian Grand Prix",
		"circuit": "Gilles Villeneuve",
		"location": "Montreal, Canada",
		"session": "Race *",
		"time": 1560081600,
		"laps": 70,
		"distance": false,
		"length": 7200
	},
	"20": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 8,
		"name": "French Grand Prix",
		"circuit": "Paul Ricard",
		"location": "Le Castellet, France",
		"session": "Race *",
		"time": 1561291200,
		"laps": 53,
		"distance": false,
		"length": 7200
	},
	"21": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 9,
		"name": "Austrian Grand Prix",
		"circuit": "Red Bull Ring",
		"location": "Spielberg, Austria",
		"session": "Race *",
		"time": 1561896000,
		"laps": 71,
		"distance": false,
		"length": 7200
	},
	"22": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 10,
		"name": "British Grand Prix",
		"circuit": "Silverstone",
		"location": "Silverstone, United Kingdom",
		"session": "Race *",
		"time": 1563105600,
		"laps": 52,
		"distance": false,
		"length": 7200
	},
	"23": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 11,
		"name": "German Grand Prix",
		"circuit": "Hockenheimring",
		"location": "Hockenheim, Germany",
		"session": "Race *",
		"time": 1564315200,
		"laps": 67,
		"distance": false,
		"length": 7200
	},
	"24": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 12,
		"name": "Hungarian Grand Prix",
		"circuit": "Hungaroring",
		"location": "Mogyoród, Hungary",
		"session": "Race *",
		"time": 1564920000,
		"laps": 70,
		"distance": false,
		"length": 7200
	},
	"25": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 13,
		"name": "Belgian Grand Prix",
		"circuit": "Spa-Francorchamps",
		"location": "Stavelot, Belgium",
		"session": "Race *",
		"time": 1567339200,
		"laps": 44,
		"distance": false,
		"length": 7200
	},
	"26": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 14,
		"name": "Italian Grand Prix",
		"circuit": "Monza",
		"location": "Monza, Italy",
		"session": "Race *",
		"time": 1567944000,
		"laps": 53,
		"distance": false,
		"length": 7200
	},
	"27": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 15,
		"name": "Singapore Grand Prix",
		"circuit": "Marina Bay",
		"location": "Marina Bay, Singapore",
		"session": "Race *",
		"time": 1569153600,
		"laps": 61,
		"distance": false,
		"length": 7200
	},
	"28": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 16,
		"name": "Russian Grand Prix",
		"circuit": "Sochi",
		"location": "Sochi, Russia",
		"session": "Race *",
		"time": 1569758400,
		"laps": 53,
		"distance": false,
		"length": 7200
	},
	"29": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 17,
		"name": "Japanese Grand Prix",
		"circuit": "Suzuka",
		"location": "Suzuka, Japan",
		"session": "Race *",
		"time": 1570968000,
		"laps": 53,
		"distance": false,
		"length": 7200
	},
	"30": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 18,
		"name": "Mexican Grand Prix",
		"circuit": "Hermanos Rodríguez",
		"location": "Mexico City, Mexico",
		"session": "Race *",
		"time": 1572177600,
		"laps": 71,
		"distance": false,
		"length": 7200
	},
	"31": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 19,
		"name": "United States Grand Prix",
		"circuit": "Circuit of the Americas",
		"location": "Austin, TX, USA",
		"session": "Race *",
		"time": 1572782400,
		"laps": 56,
		"distance": false,
		"length": 7200
	},
	"32": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 20,
		"name": "Brazilian Grand Prix",
		"circuit": "Interlagos",
		"location": "São Paulo, Brazil",
		"session": "Race *",
		"time": 1573992000,
		"laps": 71,
		"distance": false,
		"length": 7200
	},
	"33": {
		"series": "Formula 1",
		"symbol": "F1",
		"round": 21,
		"name": "Abu Dhabi Grand Prix",
		"circuit": "Yas Marina",
		"location": "Abu Dhabi, UAE",
		"session": "Race *",
		"time": 1575201600,
		"laps": 55,
		"distance": false,
		"length": 7200
	},
	// Asian LMS 2018/19 SEASON OUTLINE
	"34": {
		"series": "Asian Le Mans Series",
		"symbol": "AsianLMS",
		"round": 1,
		"name": "4h Shanghai",
		"circuit": "Shanghai",
		"location": "Shanghai, China",
		"session": "Race *",
		"time": 1543147200,
		"laps": false,
		"distance": false,
		"length": 14400
	},
	"35": {
		"series": "Asian Le Mans Series",
		"symbol": "AsianLMS",
		"round": 2,
		"name": "4h Fuji",
		"circuit": "Fuji Speedway",
		"location": "Oyama, Japan",
		"session": "Race *",
		"time": 1544356800,
		"laps": false,
		"distance": false,
		"length": 14400
	},
	"36": {
		"series": "Asian Le Mans Series",
		"symbol": "AsianLMS",
		"round": 3,
		"name": "4 Hours of Buriram",
		"circuit": "Chang International",
		"location": "Buriram, Thailand",
		"session": "Race",
		"time": 1547268300,
		"laps": false,
		"distance": false,
		"length": 14400
	},
	"37": {
		"series": "Asian Le Mans Series",
		"symbol": "AsianLMS",
		"round": 4,
		"name": "4 Hours of Sepang",
		"circuit": "Sepang International",
		"location": "Selangor, Malaysia",
		"session": "Race *",
		"time": 1551009600,
		"laps": false,
		"distance": false,
		"length": 14400
	},
	//WEC 2018/19 SEASON OUTLINE
	"38": {
		"series": "World Endurance Championship",
		"symbol": "WEC",
		"round": 06,
		"name": "1000 Miles of Sebring",
		"circuit": "Sebring",
		"location": "Sebring, FL, USA",
		"session": "Race *",
		"time": 1552651200,
		"laps": "TBD",
		"distance": false,
		"length": 7200
	},
	"39": {
		"series": "World Endurance Championship",
		"symbol": "WEC",
		"round": 07,
		"name": "6 Hours of Spa-Francorchamps",
		"circuit": "Spa-Francorchamps",
		"location": "Stavelot, Belgium",
		"session": "Race *",
		"time": 1556967600,
		"laps": false,
		"distance": false,
		"length": 21600
	},
	"40": {
		"series": "World Endurance Championship",
		"symbol": "WEC",
		"round": 08,
		"name": "24 Hours of Le Mans",
		"circuit": "la Sarthe",
		"location": "Le Mans, France",
		"session": "Race *",
		"time": 1560603600,
		"laps": false,
		"distance": false,
		"length": 86400
	},
	// FORMULA E 2018/19 SEASON ROUND 01 DETAILS
	"41": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 01,
		"name": "Ad Diriyah ePrix",
		"circuit": "Riyadh Street Circuit",
		"location": "Ad Diriyah, Saudi Arabia",
		"session": "Free Practice 1",
		"time": 1544846400,
		"laps": false,
		"distance": false,
		"length": 2700
	},
	"42": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 01,
		"name": "Ad Diriyah ePrix",
		"circuit": "Riyadh Street Circuit",
		"location": "Ad Diriyah, Saudi Arabia",
		"session": "Free Practice 2",
		"time": 1544853900,
		"laps": false,
		"distance": false,
		"length": 1800
	},
	"43": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 01,
		"name": "Ad Diriyah ePrix",
		"circuit": "Riyadh Street Circuit",
		"location": "Ad Diriyah, Saudi Arabia",
		"session": "Qualifying",
		"time": 1544860200,
		"laps": false,
		"distance": false,
		"length": 2700
	},
	"44": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 01,
		"name": "Ad Diriyah ePrix",
		"circuit": "Riyadh Street Circuit",
		"location": "Ad Diriyah, Saudi Arabia",
		"session": "Super Pole",
		"time": 1544862900,
		"laps": false,
		"distance": false,
		"length": 900
	},
	// FORMULA E 2018/19 SEASON ROUND 02 DETAILS
	"45": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 02,
		"name": "Marrakesh ePrix",
		"circuit": "Moulay El Hassan",
		"location": "Marrakesh, Morocco",
		"session": "Free Practice 1",
		"time": 1547276400,
		"laps": false,
		"distance": false,
		"length": 2700
	},
	"46": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 02,
		"name": "Marrakesh ePrix",
		"circuit": "Moulay El Hassan",
		"location": "Marrakesh, Morocco",
		"session": "Free Practice 2",
		"time": 1547284500,
		"laps": false,
		"distance": false,
		"length": 1800
	},
	"47": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 02,
		"name": "Marrakesh ePrix",
		"circuit": "Moulay El Hassan",
		"location": "Marrakesh, Morocco",
		"session": "Qualifying",
		"time": 1547290800,
		"laps": false,
		"distance": false,
		"length": 2700
	},
	"48": {
		"series": "Formula E",
		"symbol": "FE",
		"round": 02,
		"name": "Marrakesh ePrix",
		"circuit": "Moulay El Hassan",
		"location": "Marrakesh, Morocco",
		"session": "Super Pole",
		"time": 1547293500,
		"laps": false,
		"distance": false,
		"length": 900
	},
	"49": {
		"series": "Asian Le Mans Series",
		"symbol": "AsianLMS",
		"round": 3,
		"name": "4 Hours of Buriram",
		"circuit": "Chang International",
		"location": "Buriram, Thailand",
		"session": "Free Practice 1",
		"time": 1547170800,
		"laps": false,
		"distance": false,
		"length": 5400
	},
	"50": {
		"series": "Asian Le Mans Series",
		"symbol": "AsianLMS",
		"round": 3,
		"name": "4 Hours of Buriram",
		"circuit": "Chang International",
		"location": "Buriram, Thailand",
		"session": "Free Practice 2",
		"time": 1547185200,
		"laps": false,
		"distance": false,
		"length": 4800
	},
	"51": {
		"series": "Asian Le Mans Series",
		"symbol": "AsianLMS",
		"round": 3,
		"name": "4 Hours of Buriram",
		"circuit": "Chang International",
		"location": "Buriram, Thailand",
		"session": "GT Qualifying",
		"time": 1547199300,
		"laps": false,
		"distance": false,
		"length": 900
	},
	"52": {
		"series": "Asian Le Mans Series",
		"symbol": "AsianLMS",
		"round": 3,
		"name": "4 Hours of Buriram",
		"circuit": "Chang International",
		"location": "Buriram, Thailand",
		"session": "LMP2 & LMP3 Qualifying",
		"time": 1547200800,
		"laps": false,
		"distance": false,
		"length": 900
	},
	"53": {
		"series": "Race of Champions",
		"symbol": "ROC",
		"round": "",
		"name": "Race of Champions",
		"circuit": "Hermanos Rodríguez",
		"location": "Mexico City, Mexico",
		"session": "ROC Nations Cup",
		"time": 1547924400,
		"laps": false,
		"distance": false,
		"length": 10800
	},
	"54": {
		"series": "Race of Champions",
		"symbol": "ROC",
		"round": "",
		"name": "Race of Champions",
		"circuit": "Hermanos Rodríguez",
		"location": "Mexico City, Mexico",
		"session": "Race of Champions",
		"time": 1548010800,
		"laps": false,
		"distance": false,
		"length": 10800
	},
	"55": {
		"series": "Race of Champions",
		"symbol": "ROC",
		"round": "",
		"name": "Race of Champions",
		"circuit": "Hermanos Rodríguez",
		"location": "Mexico City, Mexico",
		"session": "Stadium Super Trucks ROC Final",
		"time": 1547937000,
		"laps": false,
		"distance": false,
		"length": 3600
	},
	"56": {
		"series": "Race of Champions",
		"symbol": "ROC",
		"round": "",
		"name": "Race of Champions",
		"circuit": "Hermanos Rodríguez",
		"location": "Mexico City, Mexico",
		"session": "Stadium Super Trucks ROC Final",
		"time": 1548023400,
		"laps": false,
		"distance": false,
		"length": 3600
	},
	"57": {
		"series": "SportsCar Championship",
		"symbol": "IMSASC",
		"round": "1",
		"name": "24 Hours of Daytona",
		"circuit": "Daytona combined road course",
		"location": "Daytona Beach, FL, USA",
		"session": "Practice 1 (All Classes)",
		"time": 1548343200,
		"laps": false,
		"distance": false,
		"length": 2700
	},
	"58": {
		"series": "SportsCar Championship",
		"symbol": "IMSASC",
		"round": "1",
		"name": "24 Hours of Daytona",
		"circuit": "Daytona combined road course",
		"location": "Daytona Beach, FL, USA",
		"session": "Practice 1 (GTD S/B Only)",
		"time": 1548345900,
		"laps": false,
		"distance": false,
		"length": 900
	},
	"59": {
		"series": "SportsCar Championship",
		"symbol": "IMSASC",
		"round": "1",
		"name": "24 Hours of Daytona",
		"circuit": "Daytona combined road course",
		"location": "Daytona Beach, FL, USA",
		"session": "Practice 2",
		"time": 1548354600,
		"laps": false,
		"distance": false,
		"length": 3300
	},
	"60": {
		"series": "SportsCar Championship",
		"symbol": "IMSASC",
		"round": "1",
		"name": "24 Hours of Daytona",
		"circuit": "Daytona combined road course",
		"location": "Daytona Beach, FL, USA",
		"session": "Qualifying (GTD)",
		"time": 1548362100,
		"laps": false,
		"distance": false,
		"length": 900
	},
	"61": {
		"series": "SportsCar Championship",
		"symbol": "IMSASC",
		"round": "1",
		"name": "24 Hours of Daytona",
		"circuit": "Daytona combined road course",
		"location": "Daytona Beach, FL, USA",
		"session": "Qualifying (GTLM)",
		"time": 1548363600,
		"laps": false,
		"distance": false,
		"length": 900
	},
	"61": {
		"series": "SportsCar Championship",
		"symbol": "IMSASC",
		"round": "1",
		"name": "24 Hours of Daytona",
		"circuit": "Daytona combined road course",
		"location": "Daytona Beach, FL, USA",
		"session": "Qualifying (DPi/LMP2)",
		"time": 1548365100,
		"laps": false,
		"distance": false,
		"length": 900
	},
	"62": {
		"series": "SportsCar Championship",
		"symbol": "IMSASC",
		"round": "1",
		"name": "24 Hours of Daytona",
		"circuit": "Daytona combined road course",
		"location": "Daytona Beach, FL, USA",
		"session": "Practice 3",
		"time": 1548374400,
		"laps": false,
		"distance": false,
		"length": 5400
	},
	"63": {
		"series": "SportsCar Championship",
		"symbol": "IMSASC",
		"round": "1",
		"name": "24 Hours of Daytona",
		"circuit": "Daytona combined road course",
		"location": "Daytona Beach, FL, USA",
		"session": "Practice 4",
		"time": 1548428400,
		"laps": false,
		"distance": false,
		"length": 3600
	},
	"64": {
		"series": "SportsCar Championship",
		"symbol": "IMSASC",
		"round": "1",
		"name": "24 Hours of Daytona",
		"circuit": "Daytona combined road course",
		"location": "Daytona Beach, FL, USA",
		"session": "Race",
		"time": 1548522000,
		"laps": false,
		"distance": false,
		"length": 86400
	},
	// DAKAR 2019
	"65": {
		"series": "Dakar Rally",
		"symbol": "Dakar",
		"round": "1",
		"name": "Dakar Rally",
		"circuit": "",
		"location": "Peru",
		"session": "Lima > Prisco",
		"time": 1546871400,
		"laps": false,
		"distance": "331 km",
		"length": 43200
	},
	"66": {
		"series": "Dakar Rally",
		"symbol": "Dakar",
		"round": "2",
		"name": "Dakar Rally",
		"circuit": "",
		"location": "Peru",
		"session": "Pisco > San Juan de Marcona",
		"time": 1546954440,
		"laps": false,
		"distance": "563 km",
		"length": 43200
	},
	"67": {
		"series": "Dakar Rally",
		"symbol": "Dakar",
		"round": "3",
		"name": "Dakar Rally",
		"circuit": "",
		"location": "Peru",
		"session": "San Juan de Marcona > Arequipa",
		"time": 1547030400,
		"laps": false,
		"distance": "798 km",
		"length": 43200
	},
	"68": {
		"series": "Dakar Rally",
		"symbol": "Dakar",
		"round": "4",
		"name": "Dakar Rally",
		"circuit": "",
		"location": "Peru",
		"session": "Arequipa > Moquegua",
		"time": 1547119800,
		"laps": false,
		"distance": "511 km",
		"length": 43200
	},
	"69": {
		"series": "Dakar Rally",
		"symbol": "Dakar",
		"round": "5",
		"name": "Dakar Rally",
		"circuit": "",
		"location": "Peru",
		"session": "Moquegua > Arequipa",
		"time": 1547205300,
		"laps": false,
		"distance": "776 km",
		"length": 43200
	},
	"70": {
		"series": "Dakar Rally",
		"symbol": "Dakar",
		"round": "6",
		"name": "Dakar Rally",
		"circuit": "",
		"location": "Peru",
		"session": "Arequipa > San Juan de Marcona",
		"time": 1547386200,
		"laps": false,
		"distance": "838 km",
		"length": 43200
	},
	"71": {
		"series": "Dakar Rally",
		"symbol": "Dakar",
		"round": "7",
		"name": "Dakar Rally",
		"circuit": "",
		"location": "Peru",
		"session": "San Juan de Marcona > San Juan de Marcona",
		"time": 1547463600,
		"laps": false,
		"distance": "383 km",
		"length": 43200
	},
	"72": {
		"series": "Dakar Rally",
		"symbol": "Dakar",
		"round": "8",
		"name": "Dakar Rally",
		"circuit": "",
		"location": "Peru",
		"session": "San Juan de Marcona > Pisco",
		"time": 1547553600,
		"laps": false,
		"distance": "575 km",
		"length": 43200
	},
	"73": {
		"series": "Dakar Rally",
		"symbol": "Dakar",
		"round": "9",
		"name": "Dakar Rally",
		"circuit": "",
		"location": "Peru",
		"session": "Pisco > Pisco",
		"time": 1547636400,
		"laps": false,
		"distance": "409 km",
		"length": 43200
	},
	"74": {
		"series": "Dakar Rally",
		"symbol": "Dakar",
		"round": "10",
		"name": "Dakar Rally",
		"circuit": "",
		"location": "Peru",
		"session": "Pisco > Lima",
		"time": 1547732580,
		"laps": false,
		"distance": "359 km",
		"length": 43200
	},
	// INDYCAR SERIES 2019 OUTLINE
	"75": {
		"series": "IndyCar Series",
		"symbol": "IndyCar",
		"round": 1,
		"name": "Grand Prix of St. Petersburg",
		"circuit": "Streets of St. Petersburg",
		"location": "St. Petersburg, FL, USA",
		"session": "Race *",
		"time": 1552219200,
		"laps": 110,
		"distance": false,
		"length": 7200
	},
	"76": {
		"series": "IndyCar Series",
		"symbol": "IndyCar",
		"round": 2,
		"name": "IndyCar Classic",
		"circuit": "Circuit of the Americas",
		"location": "Austin, TX, USA",
		"session": "Race *",
		"time": 1553428800,
		"laps": "TBD",
		"distance": false,
		"length": 7200
	},
	"77": {
		"series": "IndyCar Series",
		"symbol": "IndyCar",
		"round": 3,
		"name": "Grand Prix of Alabama",
		"circuit": "Barber Motorsports Park",
		"location": "Leeds, AL, USA",
		"session": "Race *",
		"time": 1554638400,
		"laps": 90,
		"distance": false,
		"length": 7200
	},
	"78": {
		"series": "IndyCar Series",
		"symbol": "IndyCar",
		"round": 4,
		"name": "Grand Prix of Long Beach",
		"circuit": "Streets of Long Beach",
		"location": "Long Beach, CA, USA",
		"session": "Race *",
		"time": 1555243200,
		"laps": 85,
		"distance": false,
		"length": 7200
	},
	"79": {
		"series": "IndyCar Series",
		"symbol": "IndyCar",
		"round": 5,
		"name": "IndyCar Grand Prix",
		"circuit": "Indianapolis Road Course",
		"location": "Speedway, IN, USA",
		"session": "Race *",
		"time": 1557576000,
		"laps": 85,
		"distance": false,
		"length": 7200
	},
	"80": {
		"series": "IndyCar Series",
		"symbol": "IndyCar",
		"round": 6,
		"name": "Indianapolis 500",
		"circuit": "Indianapolis Motor Speedway",
		"location": "Speedway, IN, USA",
		"session": "Race *",
		"time": 1558872000,
		"laps": 200,
		"distance": false,
		"length": 14400
	},
	"81": {
		"series": "IndyCar Series",
		"symbol": "IndyCar",
		"round": 7,
		"name": "Detroit Grand Prix",
		"circuit": "Belle Isle Park",
		"location": "Detroit, MI, USA",
		"session": "Race *",
		"time": 1559390400,
		"laps": 70,
		"distance": false,
		"length": 7200
	},
	"82": {
		"series": "IndyCar Series",
		"symbol": "IndyCar",
		"round": 8,
		"name": "Detroit Grand Prix",
		"circuit": "Belle Isle Park",
		"location": "Detroit, MI, USA",
		"session": "Race *",
		"time": 1559476800,
		"laps": 70,
		"distance": false,
		"length": 7200
	},
	"83": {
		"series": "IndyCar Series",
		"symbol": "IndyCar",
		"round": 9,
		"name": "Texas 600",
		"circuit": "Texas Motor Speedway",
		"location": "Fort Worth, TX, USA",
		"session": "Race *",
		"time": 1559995200,
		"laps": 248,
		"distance": false,
		"length": 7200
	},
	"84": {
		"series": "IndyCar Series",
		"symbol": "IndyCar",
		"round": 10,
		"name": "Grand Prix of Road America",
		"circuit": "Road America",
		"location": "Elkhart Lake, WI, USA",
		"session": "Race *",
		"time": 1561291200,
		"laps": 55,
		"distance": false,
		"length": 7200
	},
	"85": {
		"series": "IndyCar Series",
		"symbol": "IndyCar",
		"round": 11,
		"name": "Grand Prix of Toronto",
		"circuit": "Exhibition Place",
		"location": "Toronto, Canada",
		"session": "Race *",
		"time": 1563105600,
		"laps": 85,
		"distance": false,
		"length": 7200
	},
	"86": {
		"series": "IndyCar Series",
		"symbol": "IndyCar",
		"round": 12,
		"name": "Iowa 300",
		"circuit": "Iowa Speedway",
		"location": "Newton, IA, USA",
		"session": "Race *",
		"time": 1563624000,
		"laps": 300,
		"distance": false,
		"length": 7200
	},
	"87": {
		"series": "IndyCar Series",
		"symbol": "IndyCar",
		"round": 13,
		"name": "Grand Prix of Mid-Ohio",
		"circuit": "Mid-Ohio Sports Car Course",
		"location": "Lexington, OH, USA",
		"session": "Race *",
		"time": 1564315200,
		"laps": 90,
		"distance": false,
		"length": 7200
	},
	"88": {
		"series": "IndyCar Series",
		"symbol": "IndyCar",
		"round": 14,
		"name": "Pocono 500",
		"circuit": "Pocono Raceway",
		"location": "Long Pond, PA, USA",
		"session": "Race *",
		"time": 1566129600,
		"laps": 200,
		"distance": false,
		"length": 7200
	},
	"89": {
		"series": "IndyCar Series",
		"symbol": "IndyCar",
		"round": 15,
		"name": "Gateway 500",
		"circuit": "Gateway Motorsports Park",
		"location": "Madison, IL, USA",
		"session": "Race *",
		"time": 1566648000,
		"laps": 248,
		"distance": false,
		"length": 7200
	},
	"90": {
		"series": "IndyCar Series",
		"symbol": "IndyCar",
		"round": 16,
		"name": "Grand Prix of Portland",
		"circuit": "Portland International",
		"location": "Portland, OR, USA",
		"session": "Race *",
		"time": 1567339200,
		"laps": 105,
		"distance": false,
		"length": 7200
	},
	"91": {
		"series": "IndyCar Series",
		"symbol": "IndyCar",
		"round": 17,
		"name": "Grand Prix of Monterey",
		"circuit": "Laguna Seca",
		"location": "Monterey, CA, USA",
		"session": "Race *",
		"time": 1569153600,
		"laps": "TBD",
		"distance": false,
		"length": 7200
	},
	// WRC 01 Monte Carlo
	"92": {
		"series": "World Rally Championship",
		"symbol": "WRC",
		"round": 1,
		"name": "Rallye Monte Carlo",
		"circuit": "",
		"location": "Monte Carlo, Monaco",
		"session": "Shakedown",
		"time": 1548320400,
		"laps": false,
		"distance": "3.35 km",
		"length": 3600
	},
	"93": {
		"series": "World Rally Championship",
		"symbol": "WRC",
		"round": 1,
		"name": "Rallye Monte Carlo",
		"circuit": "",
		"location": "Monte Carlo, Monaco",
		"session": "Section 1",
		"time": 1548354900,
		"laps": false,
		"distance": "41.35 km",
		"length": 10800
	},
	"94": {
		"series": "World Rally Championship",
		"symbol": "WRC",
		"round": 1,
		"name": "Rallye Monte Carlo",
		"circuit": "",
		"location": "Monte Carlo, Monaco",
		"session": "Section 2",
		"time": 1548403200,
		"laps": false,
		"distance": "62.56 km",
		"length": 12600
	},
	"95": {
		"series": "World Rally Championship",
		"symbol": "WRC",
		"round": 1,
		"name": "Rallye Monte Carlo",
		"circuit": "",
		"location": "Monte Carlo, Monaco",
		"session": "Section 3",
		"time": 1548422400,
		"laps": false,
		"distance": "62.56 km",
		"length": 12600
	},
	"96": {
		"series": "World Rally Championship",
		"symbol": "WRC",
		"round": 1,
		"name": "Rallye Monte Carlo",
		"circuit": "",
		"location": "Monte Carlo, Monaco",
		"session": "Section 4",
		"time": 1548488700,
		"laps": false,
		"distance": "46.69 km",
		"length": 12600
	},
	"97": {
		"series": "World Rally Championship",
		"symbol": "WRC",
		"round": 1,
		"name": "Rallye Monte Carlo",
		"circuit": "",
		"location": "Monte Carlo, Monaco",
		"session": "Section 5",
		"time": 1548503100,
		"laps": false,
		"distance": "46.69 km",
		"length": 12600
	},
	"98": {
		"series": "World Rally Championship",
		"symbol": "WRC",
		"round": 1,
		"name": "Rallye Monte Carlo",
		"circuit": "",
		"location": "Monte Carlo, Monaco",
		"session": "Section 6",
		"time": 1548573300,
		"laps": false,
		"distance": "31.99 km",
		"length": 12600
	},
	"99": {
		"series": "World Rally Championship",
		"symbol": "WRC",
		"round": 1,
		"name": "Rallye Monte Carlo",
		"circuit": "",
		"location": "Monte Carlo, Monaco",
		"session": "Section 7",
		"time": 1548587700,
		"laps": false,
		"distance": "31.99 km",
		"length": 12600
	},
	// ELMS OUTLINE
	"100": {
		"series": "European Le Mans Series",
		"symbol": "ELMS",
		"round": 1,
		"name": "4 Hours of Le Castellet",
		"circuit": "Paul Ricard",
		"location": "Le Castellet, France",
		"session": "Race *",
		"time": 1555243200,
		"laps": false,
		"distance": false,
		"length": 14400
	},
	"101": {
		"series": "European Le Mans Series",
		"symbol": "ELMS",
		"round": 2,
		"name": "4 Hours of Monza",
		"circuit": "Monza",
		"location": "Monza, Italy",
		"session": "Race *",
		"time": 1557662400,
		"laps": false,
		"distance": false,
		"length": 14400
	},
	"102": {
		"series": "European Le Mans Series",
		"symbol": "ELMS",
		"round": 3,
		"name": "4 Hours of Bracelona",
		"circuit": "Barcelona-Catalunya",
		"location": "Montmeló, Spain",
		"session": "Race *",
		"time": 1563710400,
		"laps": false,
		"distance": false,
		"length": 14400
	},
	"103": {
		"series": "European Le Mans Series",
		"symbol": "ELMS",
		"round": 4,
		"name": "4 Hours of Silverstone",
		"circuit": "Silverstone",
		"location": "Silverstone, United Kingdom",
		"session": "Race *",
		"time": 1567252800,
		"laps": false,
		"distance": false,
		"length": 14400
	},
	"104": {
		"series": "European Le Mans Series",
		"symbol": "ELMS",
		"round": 5,
		"name": "4 Hours of Spa-Francorchamps",
		"circuit": "Spa-Francorchamps",
		"location": "Stavelot, Belgium",
		"session": "Race *",
		"time": 1569153600,
		"laps": false,
		"distance": false,
		"length": 14400
	},
	"105": {
		"series": "European Le Mans Series",
		"symbol": "ELMS",
		"round": 6,
		"name": "4 Hours of Portimão",
		"circuit": "Algarve International",
		"location": "Portimão, Portugal",
		"session": "Race *",
		"time": 1572177600,
		"laps": false,
		"distance": false,
		"length": 14400
	},
	// SportsCar OUTLINE
	"106": {
		"series": "SportsCar Championship",
		"symbol": "IMSASC",
		"round": 2,
		"name": "12 Hours of Sebring",
		"circuit": "Sebring",
		"location": "Sebring, FL, USA",
		"session": "Race *",
		"time": 1552737600,
		"laps": false,
		"distance": false,
		"length": 43200
	},
	"107": {
		"series": "SportsCar Championship",
		"symbol": "IMSASC",
		"round": 3,
		"name": "Grand Prix at Long Beach",
		"circuit": "Streets of Long Beach",
		"location": "Long Beach, CA, USA",
		"session": "Race *",
		"time": 1555156800,
		"laps": false,
		"distance": false,
		"length": 6000
	},
	"108": {
		"series": "SportsCar Championship",
		"symbol": "IMSASC",
		"round": 4,
		"name": "Challenge at Mid-Ohio",
		"circuit": "Mid-Ohio Sports cad course",
		"location": "Lexington, OH, USA",
		"session": "Race *",
		"time": 1557057600,
		"laps": "none announced",
		"distance": false,
		"length": 9600
	},
	"109": {
		"series": "SportsCar Championship",
		"symbol": "IMSASC",
		"round": 5,
		"name": "Detroit Grand Prix",
		"circuit": "Belle Isle Park",
		"location": "Detroit, MI, USA",
		"session": "Race *",
		"time": 1559390400,
		"laps": false,
		"distance": false,
		"length": 6000
	},
	"110": {
		"series": "SportsCar Championship",
		"symbol": "IMSASC",
		"round": 6,
		"name": "Six Hours of The Glen",
		"circuit": "Watkins Glen",
		"location": "Watkins Glen, NY, USA",
		"session": "Race *",
		"time": 1561896000,
		"laps": false,
		"distance": false,
		"length": 21600
	},
	"111": {
		"series": "SportsCar Championship",
		"symbol": "IMSASC",
		"round": 7,
		"name": "CTMP Mosport",
		"circuit": "Canadian Tire Motorsport Park",
		"location": "Bowmanville, Ontario, Canada",
		"session": "Race *",
		"time": 1562500800,
		"laps": "none announced",
		"distance": false,
		"length": 9600
	},
	"112": {
		"series": "SportsCar Championship",
		"symbol": "IMSASC",
		"round": 8,
		"name": "Northeast Grand Prix",
		"circuit": "Lime Rock Park",
		"location": "Lakeville, CT, USA",
		"session": "Race *",
		"time": 1563624000,
		"laps": "none announced",
		"distance": false,
		"length": 9600
	},
	"113": {
		"series": "SportsCar Championship",
		"symbol": "IMSASC",
		"round": 9,
		"name": "Road America",
		"circuit": "Road America",
		"location": "Elkhart Lake, WI, USA",
		"session": "Race *",
		"time": 1564920000,
		"laps": "none announced",
		"distance": false,
		"length": 9600
	},
	"114": {
		"series": "SportsCar Championship",
		"symbol": "IMSASC",
		"round": 10,
		"name": "GT Challenge at VIR",
		"circuit": "Virginia International Raceway",
		"location": "Alton, VA, USA",
		"session": "Race *",
		"time": 1566734400,
		"laps": "none announced",
		"distance": false,
		"length": 9600
	},
	"115": {
		"series": "SportsCar Championship",
		"symbol": "IMSASC",
		"round": 11,
		"name": "Laguna Seca",
		"circuit": "Laguna Seca",
		"location": "Monterey, CA, USA",
		"session": "Race *",
		"time": 1568548800,
		"laps": "none announced",
		"distance": false,
		"length": 9600
	},
	"116": {
		"series": "SportsCar Championship",
		"symbol": "IMSASC",
		"round": 12,
		"name": "Petit Le Mans",
		"circuit": "Road Atlanta",
		"location": "Braselton, GA, USA",
		"session": "Race *",
		"time": 1570881600,
		"laps": false,
		"distance": false,
		"length": 36000
	},
}